### ISSUE TITLE
Still active

### ISSUE THREAD

**Issue by tonypartridge** [eighty9nine/filament-approvals#11]
Are you still active @eighty9nine ? Discord and github remaining un-reponded too.

**Comment by eighty9nine** [comment]
Yes, I am still active and maintaining the project, have just been swamped lately

**Comment by tonypartridge** [comment]
> Yes, I am still active and maintaining the project, have just been swamped lately

Ahh fab stuff! hoping to extend / work on this package too.

**Comment by eighty9nine** [comment]
Contributions are welcome, there are several issues to be handled as well
