### ISSUE TITLE
Call to a member function table() on array

### ISSUE THREAD

**Issue by threecolors-lab** [eighty9nine/filament-approvals#12]
I get error: Call to a member function table() on array

![image](https://github.com/eighty9nine/filament-approvals/assets/149889332/f6617bf2-d68f-4366-9bda-d33f6e07b665)

How to fix that?

**Comment by threecolors-lab** [comment]
It just needs a little adjustment with the available guidance.

**Comment by eighty9nine** [comment]
Have you been able to resolve this issue? If not, please share the full table function, and the full error stack.

**Comment by tonypartridge** [comment]
Yeah this is an issue still unfortunately going from the docs. I'll try and review it @eighty9nine

**Comment by tonypartridge** [comment]
@threecolors-lab @eighty9nine issue is down to returning an array when you have additional actions. 

if you did:

```php
->actions(array_merge(\EightyNine\Approvals\Tables\Actions\ApprovalActions::make(
                \Filament\Tables\Actions\Action::make('Reject')->action('reject')->label('test')
            ), [
            // Your actions
            ]),
```

It will work as desired. 

But we really need to handle this better

**Comment by eighty9nine** [comment]
Thanks @tonypartridge
