### ISSUE TITLE
Old data

### ISSUE THREAD

**Issue by todo4learn** [eighty9nine/filament-approvals#17]
How can I approve model instances already saved before the package installation and their workflow created ?
Because in my case, when I try to make the validation nothing happens.

Help me please.

**Comment by tonypartridge** [comment]
Can you provide more details please

**Comment by todo4learn** [comment]
Okay, I have my database already populated with some data in my case in my table user_licenses and after trying to make an approval system, I found out your package and installed it. Then I configured my model UserLicense and created the approval flow and steps. But when I click on the button "Done" nothing happens with my existing data. I don't know if I explain well my issue. So I want to know if there's a way to fix it. Thanks

**Comment by tonypartridge** [comment]
It sounds like the because the model has not been created with the approvals package, you haven't start the flow process. So you would need to manually add them, so I would suggest you write a migrate to start them? And use similar to the boot of the approvable trait.

```php

            $model->approvalStatus()->create([
                'steps' => $model->approvalFlowSteps()->map(function ($item) {
                    $set = $item->only(['id', 'role_id', 'action']);
                    $set['process_approval_id'] = null;
                    $set['role_name'] = $item->role?->name ?? $item->role_id;
                    $set['process_approval_action'] = null;
                    return $set;
                }),
                'status' => (property_exists($model, 'autoSubmit') && $model->autoSubmit) ? ApprovalStatusEnum::SUBMITTED->value : ApprovalStatusEnum::CREATED->value,
                'creator_id' => Auth::id(),
            ]);
            ```

**Comment by todo4learn** [comment]
Can you please tell me how and where to do so ?

**Comment by tonypartridge** [comment]
Write a Laravel migration:

php artisan make:migration migrate_approval_models_to_approvables

edit the file and do something like:

```php
 \App\Models\MyModel::where('state', null)->each(function ($model) {
 
             $model->approvalStatus()->create([
                'steps' => $model->approvalFlowSteps()->map(function ($item) {
                    $set = $item->only(['id', 'role_id', 'action']);
                    $set['process_approval_id'] = null;
                    $set['role_name'] = $item->role?->name ?? $item->role_id;
                    $set['process_approval_action'] = null;
                    return $set;
                }),
                'status' => (property_exists($model, 'autoSubmit') && $model->autoSubmit) ? ApprovalStatusEnum::SUBMITTED->value : ApprovalStatusEnum::CREATED->value,
                'creator_id' => Auth::id(),
            ]);
       }); 
 ```

**Comment by todo4learn** [comment]
<img width="1113" alt="Capture d’écran 2024-05-22 à 10 57 32" src="https://github.com/eighty9nine/filament-approvals/assets/66797699/eda1445e-5749-4ead-8d5e-cedf440a21e8">

Hello @tonypartridge here's the error I got when I try to execute the migration file. My eightynine/filament-approvals version in my composer.json is "^3.1"
