### ISSUE TITLE
Real life example required.

### ISSUE THREAD

**Issue by aliaxonbaig** [eighty9nine/filament-approvals#18]
I have gone through the documentation a couple of times and didn't grasp the flow of approvals in its entirety. May I ask the author or someone else with implementation knowledge to post a real-world implementation example. 

What I want to achieve:

A location recorded is created
Approval is auto started as per the approval step defined
All approvers approve the approval
Finally, the status of location is set to active, a custom notification is sent to the initiator. 

Current Setup:
Filament v3, filament-approvals correctly setup:

**Comment by tonypartridge** [comment]
Hello,

So this package uses https://github.com/ringlesoft/laravel-process-approval

Once you have created the flow and the steps i.e. the steps would be require approval from role X, then role Y, then role Z, then have a step to mark active which you could make happen automatically one the 3rd approver approving which completes it an marks it as active and the notification can then be sent.

**Comment by eighty9nine** [comment]
@aliaxonbaig Povilas has made a good video about the package https://youtu.be/HSHyCaWlY5w?si=UtfnSBoGAkg-9Lo-

**Comment by aliaxonbaig** [comment]
Thank you for your responses and references, that helped indeed!

I'm wondering how to achieve the below:

I have a model named "Incidents" and I have created the flow and added everything,

When I create a record in incident table the approved column is null.


What I want:

When the approval process is completed through the approval flow, the approved column should be marked as approved as part of approval completion step and the original requester should bet a database notification.

Thanks in advance!

**Comment by eighty9nine** [comment]
In your model 'Incidents' you can define an onApprovalCompleted() method, and inside 

```php
    public function onApprovalCompleted(ProcessApproval $approval): bool
    {
        // Write logic to be executed when the approval process is completed
        // For example:
        $this->update([
           "status" => "approved"
        ]);
        return true;
    }

```

**Comment by aliaxonbaig** [comment]
And how and from where this function would be triggered?

**Comment by tonypartridge** [comment]
> And how and from where this function would be triggered?

It is a callback method, see: https://github.com/ringlesoft/laravel-process-approval?tab=readme-ov-file#3-implement-the-onapprovalcompleted-method

**Comment by eighty9nine** [comment]
As @tonypartridge explained, the method is triggered once your approval flow is complete, once the last approver approves.

**Comment by aliaxonbaig** [comment]
I tried the function is incompatable with what you have it says!

**Comment by tonypartridge** [comment]
Can you provie your model code as that's not making sense, I suspect your ProcessApproval is imported wrong.

**Comment by aliaxonbaig** [comment]
> Can you provie your model code as that's not making sense, I suspect your ProcessApproval is imported wrong.

![image](https://github.com/eighty9nine/filament-approvals/assets/52659978/90728e38-7efe-42c7-b064-66d7a586b205)



By importing "use RingleSoft\LaravelProcessApproval\Models\ProcessApproval" the incompatibility issue seems gone but the dd() is never triggered as if the function is never called at least the one I've overridden in my model class.



@eighty9nine any suggestions please? 


Thanks

**Comment by aliaxonbaig** [comment]
The above approach worked as is, my bad, I didn't check it properly.

**Comment by aliaxonbaig** [comment]
Strange enough, when the approval process has any approval flows defined, the onApprovalCompleted() on model is not called.

![image](https://github.com/eighty9nine/filament-approvals/assets/52659978/9439e4fa-dd80-4ff7-9268-14ba8e5e90d4)


Model record right after submit but before clicking the approve button

![image](https://github.com/eighty9nine/filament-approvals/assets/52659978/8ac7e827-c0bf-4b9f-ad76-308224fd20d7)


Now I define approval flow for the Model:

![image](https://github.com/eighty9nine/filament-approvals/assets/52659978/a8686e6c-2a13-4c3e-86ba-33ee6313d01f)




Now when I defined an approval flow and then approve the update is not executed as onApprovalComplete() in my model is not called.
![image](https://github.com/eighty9nine/filament-approvals/assets/52659978/3396e3f4-8097-4ac5-9718-1f78b8c52718)

Print Contract custom action is only available to records where the approved = true 


Regards

**Comment by eighty9nine** [comment]
The ability to debug is limited due to limited information, and looks to be project specific.
