### ISSUE TITLE
Syntax error: syntax error at or near "order" - PostgreSQL & Backticks

### ISSUE THREAD

**Issue by danielgnh** [eighty9nine/filament-approvals#19]
![image](https://github.com/eighty9nine/filament-approvals/assets/33636385/61d963ec-8e62-4802-9cb6-4893a3c2f06f)

Using PostgreSQL i'm getting an error when sorting SQL query by the order column because of the backticks that are used in the query.

 PostgreSQL against MySQL uses double quotes for quoting identifiers, so PostgreSQL does not recognize it.

```
Syntax error           Query response

ORDER BY 
  `ORDER` ASC,   ==>   "ORDER" ASC, 
  id ASC
```

What do you think would be the best solution for this problem?

**Comment by eighty9nine** [comment]
This has been fixed by the auther of the package laravel-process-approval!
