### ISSUE TITLE
Add other data like reports to the approval 

### ISSUE THREAD

**Issue by T3mmyKay** [eighty9nine/filament-approvals#20]
I want to be able to add comment and other data necessary to approval

**Comment by tonypartridge** [comment]
Go to config/approvals.php

enable_approval_comments => true

**Comment by T3mmyKay** [comment]
Can I also include attachments like images

**Comment by tonypartridge** [comment]
No, you’d need to override the method and build your own for that.

Many thanks
Tony

**Comment by T3mmyKay** [comment]
Can you please give me a guide about how to go about that

**Comment by eighty9nine** [comment]
Hello @T3mmyKay  please continue this discussion in the discover server of the plugin
