### ISSUE TITLE
How can I use this on multi-tenancy?

### ISSUE THREAD

**Issue by paulmercs** [eighty9nine/filament-approvals#23]
I am trying to use this plugin on my app but unfortunately it's not working.. added team_id column on process_approval_flows table.

**Comment by tonypartridge** [comment]
Ironically no, see:
https://github.com/ringlesoft/laravel-process-approval/issues/24#issuecomment-2179904583

**Comment by paulmercs** [comment]
i badly needed this feature. i am trying to configure it but won't work. can you help me?

**Comment by eighty9nine** [comment]
Please update the package and you will receive an update with this feature: https://github.com/ringlesoft/laravel-process-approval/issues/24#issuecomment-2229180158
