### ISSUE TITLE
"VERIFY" is not a valid backing value for enum "RingleSoft\LaravelProcessApproval\Enums\ApprovalTypeEnum"

### ISSUE THREAD

**Issue by billydekid** [eighty9nine/filament-approvals#26]
Hi,
As subject, I have that error message when my flow contains "VERIFY" action step.
The record will create successfully but the Approval status column value is "No Status Exists" and status is "Done", no Approval actions list (Approve or Reject).

Following is the laravel.log for that error:
```
[2024-07-22 10:16:26] local.ERROR: "VERIFY" is not a valid backing value for enum "RingleSoft\LaravelProcessApproval\Enums\ApprovalTypeEnum" {"userId":1,"exception":
"[object] (ValueError(code: 0): \"VERIFY\" is not a valid backing value for enum \"RingleSoft\\LaravelProcessApproval\\Enums\\ApprovalTypeEnum\" at /home/alfresco/do
cflow.bw.intranet/vendor/ringlesoft/laravel-process-approval/src/DataObjects/ApprovalStatusStepData.php:96)
[stacktrace]
```

I use Filament v3.2.95, Laravel v10.48.16 and PHP 8.1.2.

Thanks,
[bayu]

**Comment by tonypartridge** [comment]
You have added a VERIFY state but ApprovalTypeEnum doesn't have a VERIFY state..

**Comment by billydekid** [comment]
Hi,

Solved by add VERIFY state in /vendor/ringlesoft/laravel-process-approval/src/Enums/ApprovalTypeEnum.php file.

Thanks @tonypartridge

**Comment by billydekid** [comment]
Note to do: I will extends that class for final solution.
