### ISSUE TITLE
How to hide Approval Flows menu?

### ISSUE THREAD

**Issue by billydekid** [eighty9nine/filament-approvals#27]
Hi,

We can hide the menu by set to false on config/approvals.php file:
`"should_register_navigation" => true,`

But it will hide from all users.
Even I have configured it using Shield, the menu still appears. It seems the menu can't be accessed/controlled by Shield.

How the proper way to hide the Approval Flows menu by user's role?

Thanks,

**Comment by tonypartridge** [comment]
Add a Laravel Policy and it'll hide it.

**Comment by billydekid** [comment]
> Add a Laravel Policy and it'll hide it.

Okay, I will try it later. Since I'm new on Laravel/Filament and the Model itself is placed on different directory, the process of Policy creation will harder for me :(

Thanks,

**Comment by tonypartridge** [comment]
> > Add a Laravel Policy and it'll hide it.
> 
> Okay, I will try it later. Since I'm new on Laravel/Filament and the Model itself is placed on different directory, the process of Policy creation will harder for me :(
> 
> Thanks,

You just scope it to  the vendor model :-)

**Comment by rizalahmaddd** [comment]
hello, i already make laravel policy but why still not working?
`class ProcessApprovalFlowPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any models.
     */
    public function viewAny(User $user): bool
    {
        return $user->can('view_any_approval::flow');
    }

    /**
     * Determine whether the user can view the model.
     */
    public function view(User $user, ProcessApprovalFlow $processApprovalFlow): bool
    {
        return $user->can('view_approval::flow');
    }

    /**
     * Determine whether the user can create models.
     */
    public function create(User $user): bool
    {
        return $user->can('create_approval::flow');
    }

    /**
     * Determine whether the user can update the model.
     */
    public function update(User $user, ProcessApprovalFlow $processApprovalFlow): bool
    {
        return $user->can('update_approval::flow');
    }

    /**
     * Determine whether the user can delete the model.
     */
    public function delete(User $user, ProcessApprovalFlow $processApprovalFlow): bool
    {
        return $user->can('delete_approval::flow');
    }

    /**
     * Determine whether the user can bulk delete.
     */
    public function deleteAny(User $user): bool
    {
        return $user->can('delete_any_approval::flow');
    }

    /**
     * Determine whether the user can permanently delete.
     */
    public function forceDelete(User $user, ProcessApprovalFlow $processApprovalFlow): bool
    {
        return $user->can('force_delete_approval::flow');
    }

    /**
     * Determine whether the user can permanently bulk delete.
     */
    public function forceDeleteAny(User $user): bool
    {
        return $user->can('force_delete_any_approval::flow');
    }

    /**
     * Determine whether the user can restore.
     */
    public function restore(User $user, ProcessApprovalFlow $processApprovalFlow): bool
    {
        return $user->can('restore_approval::flow');
    }

    /**
     * Determine whether the user can bulk restore.
     */
    public function restoreAny(User $user): bool
    {
        return $user->can('restore_any_approval::flow');
    }

    /**
     * Determine whether the user can replicate.
     */
    public function replicate(User $user, ProcessApprovalFlow $processApprovalFlow): bool
    {
        return $user->can('replicate_approval::flow');
    }

    /**
     * Determine whether the user can reorder.
     */
    public function reorder(User $user): bool
    {
        return $user->can('reorder_approval::flow');
    }
}

`

**Comment by tonypartridge** [comment]
Did you register the policy since the models in vendor it won’t
auto-register?

Many thanks
Tony

**Comment by rizalahmaddd** [comment]
I hadn't registered the model yet, but after registering it, it worked. Thank you!

**Comment by nafiswatsiq** [comment]
> I hadn't registered the model yet, but after registering it, it worked. Thank you!

can you tell me how? I still can't, thank you

**Comment by rizalahmaddd** [comment]
> > I hadn't registered the model yet, but after registering it, it worked. Thank you!
> 
> can you tell me how? I still can't, thank you

on AppServiceProvider.php 
`    public function boot(): void
    {
        // the new policy
        Gate::policy(ProcessApprovalFlow::class, ProcessApprovalFlowPolicy::class);
    }`

**Comment by rizalahmaddd** [comment]
i add to my AppServiceProvider.php


`    public function boot(): void
    {
        Gate::policy(ProcessApprovalFlow::class, ProcessApprovalFlowPolicy::class);
    }`

**Comment by rizalahmaddd** [comment]
> > I hadn't registered the model yet, but after registering it, it worked. Thank you!
> 
> can you tell me how? I still can't, thank you

on my AppServiceProvider.php


`    public function boot(): void
    {
        Gate::policy(ProcessApprovalFlow::class, ProcessApprovalFlowPolicy::class);
    }`

**Comment by nafiswatsiq** [comment]
> > > I hadn't registered the model yet, but after registering it, it worked. Thank you!
> > 
> > 
> > can you tell me how? I still can't, thank you
> 
> on my AppServiceProvider.php
> 
> ` public function boot(): void { Gate::policy(ProcessApprovalFlow::class, ProcessApprovalFlowPolicy::class); }`

Thanks, it worked
