### ISSUE TITLE
Add the `NavigationGroup` of resource to make part of localization 

### ISSUE THREAD

**Issue by MarJose123** [eighty9nine/filament-approvals#6]
Hi, Can you make the navigation group of the resource to be able to translate.

https://github.com/eighty9nine/filament-approvals/blob/8946ec1e46596129c0b747cf9d1e022bcd57a159/src/Filament/Resources/ApprovalFlowResource.php#L29C50-L29C63

**Comment by tonypartridge** [comment]
Resolved in #14 please close.

**Comment by eighty9nine** [comment]
Thank you, I have seen
