### ISSUE TITLE
how to git Rejected comment

### ISSUE THREAD

**Issue by bo3bdo** [eighty9nine/filament-approvals#8]
how to git Rejected comment

![image](https://github.com/eighty9nine/filament-approvals/assets/5271380/38c0dd40-2008-4361-abc8-f848c8218c50)
 
And How To translations The ApprovalActions

**Comment by tonypartridge** [comment]
It's in the action itself. Where do you want to get it?

**Comment by tonypartridge** [comment]
Now visible by clicking the status column.
@eighty9nine  please close.
