### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails

### ISSUE THREAD

**Issue by DeviJv** [eighty9nine/filament-approvals#9]
i Try to delete flow and thats happend
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails

**Comment by noumansarwarr** [comment]
@DeviJv Did you solved this error/?

**Comment by DeviJv** [comment]
because its null bro
